# Generated by scripts/gen-docassemble.js from decision-spec.json.
# The same worked examples the Python parity test uses, expressed for ALKiln.
# Not run: ALKiln needs a Docassemble server.

Feature: SNAP work rules screening reaches the right outcome

  Scenario: Nothing answered
    Given I start the interview at "snap_abawd.yml"
    Then the variable "outcome" should be "notexempt"

  Scenario: Pregnant
    Given I start the interview at "snap_abawd.yml"
    And I set the variables to these values
      | var | value |
      | pregnant | yes |
    Then the variable "outcome" should be "exempt"

  Scenario: Lives with a child under 14
    Given I start the interview at "snap_abawd.yml"
    And I set the variables to these values
      | var | value |
      | child14 | yes |
    Then the variable "outcome" should be "exempt"

  Scenario: Earns $217.50 a week or more
    Given I start the interview at "snap_abawd.yml"
    And I set the variables to these values
      | var | value |
      | working | income_weekly |
    Then the variable "outcome" should be "exempt"

  Scenario: 30+ hours below minimum wage
    Given I start the interview at "snap_abawd.yml"
    And I set the variables to these values
      | var | value |
      | working | hours_30 |
    Then the variable "outcome" should be "exempt"

  Scenario: Gets SSI or SSDI
    Given I start the interview at "snap_abawd.yml"
    And I set the variables to these values
      | var | value |
      | disability | ssi_ssdi |
    Then the variable "outcome" should be "exempt"

  Scenario: Other disability payment only
    Given I start the interview at "snap_abawd.yml"
    And I set the variables to these values
      | var | value |
      | disability | other |
    Then the variable "outcome" should be "exempt"

  Scenario: No place to sleep, no diploma
    Given I start the interview at "snap_abawd.yml"
    And I set the variables to these values
      | var | value |
      | housing | no |
      | housingFollowup | steady_job |
    Then the variable "outcome" should be "exempt"

  Scenario: No place to sleep, diploma and steady job
    Given I start the interview at "snap_abawd.yml"
    And I set the variables to these values
      | var | value |
      | housing | no |
      | housingFollowup | diploma,steady_job |
    Then the variable "outcome" should be "notexempt"

  Scenario: No place to sleep, none of these apply
    Given I start the interview at "snap_abawd.yml"
    And I set the variables to these values
      | var | value |
      | housing | no |
      | housingFollowup | __none |
    Then the variable "outcome" should be "exempt"

  Scenario: Safety concern
    Given I start the interview at "snap_abawd.yml"
    And I set the variables to these values
      | var | value |
      | dv | yes |
    Then the variable "outcome" should be "exempt"

  Scenario: Several exemptions at once
    Given I start the interview at "snap_abawd.yml"
    And I set the variables to these values
      | var | value |
      | child14 | yes |
      | pregnant | yes |
      | working | income_weekly |
    Then the variable "outcome" should be "exempt"

  Scenario: No exemption, transport problem
    Given I start the interview at "snap_abawd.yml"
    And I set the variables to these values
      | var | value |
      | goodcause | transport |
    Then the variable "outcome" should be "goodcause"

  Scenario: No exemption, no good cause
    Given I start the interview at "snap_abawd.yml"
    And I set the variables to these values
      | var | value |
      | goodcause | __none |
    Then the variable "outcome" should be "notexempt"

  Scenario: Not 18 through 64
    Given I start the interview at "snap_abawd.yml"
    And I set the variables to these values
      | var | value |
      | ageRange | no |
    Then the variable "outcome" should be "ageexempt"

  Scenario: Is 18 through 64, nothing else answered
    Given I start the interview at "snap_abawd.yml"
    And I set the variables to these values
      | var | value |
      | ageRange | yes |
    Then the variable "outcome" should be "notexempt"

  Scenario: Not 18 through 64, and other exemptions answered
    Given I start the interview at "snap_abawd.yml"
    And I set the variables to these values
      | var | value |
      | ageRange | no |
      | pregnant | yes |
      | goodcause | transport |
    Then the variable "outcome" should be "ageexempt"

