#!/usr/bin/env node
/**
 * Generates DECISION-SPEC.md and decision-spec.json: what the screening decides
 * and why, derived by running the engine rather than by reading it.
 *
 *   "$LOCALAPPDATA/OpenAI/Codex/bin/node.exe" scripts/decision-spec.js
 *
 * Two audiences, which is why it is generated and not written by hand.
 *
 * A subject matter expert has to confirm the rules are right, and cannot be
 * asked to read JavaScript to do it. Every table here is produced by calling the
 * real functions, so it cannot describe behaviour the code does not have.
 *
 * A developer has to port this to a Docassemble interview for Court Forms
 * Online. The JSON is the machine-readable half, so the YAML can be generated
 * instead of transcribed, and the worked examples at the end are directly usable
 * as ALKiln scenarios.
 *
 * Nothing here is legal review. It states what the code does. Whether that
 * matches Massachusetts SNAP policy is exactly the open question.
 */
'use strict';

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const S = require(path.join(ROOT, 'court-forms', 'snap-screening-logic.js'));
const VARIANT = 'classic2';
const A = S.create(VARIANT);
const NONE = S.NONE;

const lines = [];
const w = s => lines.push(s);
const blank = () => lines.push('');
const section = t => { blank(); w('## ' + t); blank(); };

/* Every fact below comes from calling these two. */
const outcome = answers => A.resultType(answers);
const reasons = answers => A.exemptReasons(answers);

const json = { variant: VARIANT, generated: 'by scripts/decision-spec.js' };

w('# SNAP ABAWD screening: decision specification');
blank();
w('What the screening decides, and on what input. Generated by running the engine, so it');
w('describes real behaviour rather than intended behaviour.');
blank();
w('This is not legal review. It says what the code does. Whether that matches Massachusetts');
w('SNAP policy is the open question, and the Citation column in the tables below is where an');
w('expert records the authority for each rule. Every row is currently blank.');
blank();
w('Companion file `decision-spec.json` holds the same structure for a port to generate from.');

/* ------------------------------------------------------------------ *
 * Outcomes and precedence
 * ------------------------------------------------------------------ */
section('The four outcomes, and which one wins');

/* Prove the precedence rather than assert it: build inputs that satisfy more
 * than one condition at once and report what actually comes out. */
const PRECEDENCE = [
  {
    what: 'Age answered "no", and an exemption also applies',
    answers: { ageRange: 'no', pregnant: 'yes', goodcause: 'transport' }
  },
  {
    what: 'An exemption applies, and a good cause reason is also given',
    answers: { pregnant: 'yes', goodcause: 'transport' }
  },
  {
    what: 'No exemption, good cause given',
    answers: { goodcause: 'transport' }
  },
  {
    what: 'No exemption, good cause explicitly none',
    answers: { goodcause: NONE }
  },
  { what: 'Nothing answered at all', answers: {} }
];
w('| Input | Outcome |');
w('|---|---|');
for (const c of PRECEDENCE) w('| ' + c.what + ' | `' + outcome(c.answers) + '` |');
blank();
w('So the order is: age first, then exemption, then good cause, then not exempt. Age');
w('outranks everything, including an exemption the person also qualifies for.');
blank();
w('`ageinfo` and `exempt` both skip the good cause question entirely, because it cannot');
w('change the outcome:');
blank();
w('| Outcome | Good cause question asked |');
w('|---|---|');
for (const c of [
  { a: { ageRange: 'no' }, label: 'ageinfo' },
  { a: { pregnant: 'yes' }, label: 'exempt' },
  { a: {}, label: 'notexempt so far' }
]) {
  w('| ' + c.label + ' | ' + (A.shouldSkipGoodCause(c.a) ? 'no' : 'yes') + ' |');
}
blank();
json.outcomes = {
  order: ['ageinfo', 'exempt', 'goodcause', 'notexempt'],
  ageinfoWhen: "answers.ageRange === 'no'",
  exemptWhen: 'exemptReasons(answers).length > 0',
  goodcauseWhen: "answers.goodcause is set and is not the none sentinel ('" + NONE + "')",
  notexemptWhen: 'none of the above',
  goodCauseSkippedFor: ['ageinfo', 'exempt']
};

/* ------------------------------------------------------------------ *
 * Simple exemption triggers
 * ------------------------------------------------------------------ */
section('Exemptions from a single yes/no answer');

w('Each of these makes someone exempt on its own. The reason text is what appears on the');
w('results screen and in the printable statement.');
blank();
w('| Question | Exempt when | Reason recorded | Citation |');
w('|---|---|---|---|');
json.simpleExemptions = [];
const SPECIAL = ['housing', 'housingFollowup', 'working', 'disability'];
for (const q of A.QUESTIONS) {
  if (!q.exemptOn || SPECIAL.includes(q.id)) continue;
  const r = reasons({ [q.id]: q.exemptOn });
  w('| `' + q.id + '` | answer is "' + q.exemptOn + '" | ' + r.join('; ') + ' | |');
  json.simpleExemptions.push({ id: q.id, exemptOn: q.exemptOn, reasons: r, text: q.text });
}
blank();
w('Any question not listed here cannot produce an exemption by itself. `housing`,');
w('`housingFollowup`, `working`, and `disability` are handled separately below, because');
w('their answers are not a plain yes or no.');
blank();

/* ------------------------------------------------------------------ *
 * Work
 * ------------------------------------------------------------------ */
section('Work and income');

w('One question, pick one. All three options lead to exempt, by two different routes.');
blank();
w('| Option | Label | Exempt | Reason recorded | Citation |');
w('|---|---|---|---|---|');
json.workOptions = [];
const workQ = A.Q_BY_ID.working;
for (const o of workQ.options) {
  const r = reasons({ working: o.id });
  w('| `' + o.id + '` | ' + o.label + ' | ' + (r.length ? 'yes' : 'no') + ' | ' + r.join('; ') + ' | |');
  json.workOptions.push({ id: o.id, label: o.label, kind: A.workOptionKind(o.id), reasons: r });
}
const noneWork = reasons({ working: NONE });
w('| none of these | ' + workQ.noneLabel + ' | ' + (noneWork.length ? 'yes' : 'no') + ' | ' + (noneWork.join('; ') || 'none') + ' | |');
blank();
w('Worth an expert\'s attention: `hours_30` means 30 or more hours a week while earning');
w('*less* than minimum wage, and it currently routes to exempt on its own. Whether that is');
w('right is an open question already recorded in README.md.');
blank();

/* ------------------------------------------------------------------ *
 * Disability
 * ------------------------------------------------------------------ */
section('Disability benefits');

w('Check all that apply. Every option is exempting, but they do not all record the same');
w('reason: the named benefits collapse into one reason, and "other" adds a second asking DTA');
w('to review it.');
blank();
w('| Option | Label | Reason recorded | Citation |');
w('|---|---|---|---|');
json.disabilityOptions = [];
for (const o of A.Q_BY_ID.disability.options) {
  const r = reasons({ disability: [o.id] });
  w('| `' + o.id + '` | ' + o.label + ' | ' + r.join('; ') + ' | |');
  json.disabilityOptions.push({ id: o.id, label: o.label, reasons: r });
}
blank();
const bothDis = reasons({ disability: ['ssi_ssdi', 'other'] });
w('Selecting a named benefit and "other" together records both reasons: ' + bothDis.join('; ') + '.');
blank();

/* ------------------------------------------------------------------ *
 * Housing: exhaustive, because this is the subtle one
 * ------------------------------------------------------------------ */
section('Housing, and the unable-to-work follow-up');

w('This is the only branch whose behaviour is hard to predict by reading it, so every');
w('possible input is enumerated below rather than summarised.');
blank();
w('The follow-up is only asked when `housing` is answered "no", meaning no regular place to');
w('sleep. Answering "yes" to `housing` never produces an exemption:');
blank();
w('- `housing` = yes: ' + (reasons({ housing: 'yes' }).length ? 'exempt' : 'not exempt') + '');
w('- `housing` = no, follow-up not answered: ' + (reasons({ housing: 'no' }).length ? 'exempt' : 'not exempt'));
blank();
w('The follow-up options describe things that suggest someone *can* work, so the logic is');
w('inverted: lacking them is what points to an exemption.');
blank();

const HOPTS = A.Q_BY_ID.housingFollowup.options.map(o => o.id);
w('Option ids, in the order shown: ' + HOPTS.map(i => '`' + i + '`').join(', ') + '.');
blank();
w('| Selected follow-up options | Exempt | Citation |');
w('|---|---|---|');
json.housingTruthTable = [];
// Every subset of the follow-up options, plus the explicit none sentinel.
const subsets = [];
for (let mask = 0; mask < (1 << HOPTS.length); mask++) {
  subsets.push(HOPTS.filter((_, i) => mask & (1 << i)));
}
for (const sel of subsets) {
  const ex = S.housingUnableExempt({ housing: 'no', housingFollowup: sel });
  const label = sel.length ? sel.map(i => '`' + i + '`').join(', ') : '*(none checked)*';
  w('| ' + label + ' | ' + (ex ? 'yes' : 'no') + ' | |');
  json.housingTruthTable.push({ selected: sel, exempt: ex });
}
const exNone = S.housingUnableExempt({ housing: 'no', housingFollowup: NONE });
w('| *"none of these apply to me"* | ' + (exNone ? 'yes' : 'no') + ' | |');
json.housingTruthTable.push({ selected: NONE, exempt: exNone });
blank();

/* State the rule in words, then check the words against the table. */
const hasDiploma = s => s.includes('diploma');
const hasJobOrSchool = s => s.includes('steady_job') || s.includes('full_time_student');
const hasHealth = s => s.includes('hospitalized') || s.includes('ongoing_care');
const stated = s => (s.length === 0 ? false : hasHealth(s) || !hasDiploma(s) || !hasJobOrSchool(s));
const mismatches = subsets.filter(s => stated(s) !== S.housingUnableExempt({ housing: 'no', housingFollowup: s }));

w('In words: someone with no regular place to sleep is treated as possibly unable to work');
w('unless they checked a high school diploma **and** either a steady job or full-time study,');
w('**and** checked neither hospitalisation nor ongoing care. Checking nothing at all is');
w('treated as unanswered, not as "none apply".');
blank();
w(mismatches.length
  ? '**That description does not match the table** for ' + mismatches.length + ' input(s), which means this document is wrong and needs fixing: ' + JSON.stringify(mismatches)
  : 'That description was checked against all ' + subsets.length + ' rows above and agrees with every one.');
blank();
w('Two things for an expert here. The empty selection and the explicit "none of these"');
w('option produce opposite results, which is correct but easy to misread. And this branch');
w('records a reason asking DTA to review, rather than asserting an exemption outright.');
blank();

/* ------------------------------------------------------------------ *
 * Good cause
 * ------------------------------------------------------------------ */
section('Good cause');

w('Asked only when the answers so far point to neither an exemption nor the age outcome.');
w('Pick one.');
blank();
w('| Option | Outcome | Citation |');
w('|---|---|---|');
json.goodCauseOptions = [];
for (const o of A.GOODCAUSE.options) {
  const rt = outcome({ goodcause: o.id });
  w('| `' + o.id + '` | `' + rt + '` | |');
  json.goodCauseOptions.push({ id: o.id, label: o.label, outcome: rt, statementText: A.GC_TEXT[o.id] || '' });
}
w('| *none of these* | `' + outcome({ goodcause: NONE }) + '` | |');
blank();
w('Good cause never produces an exemption. It produces a different result screen, and a');
w('different printable statement.');
blank();

/* ------------------------------------------------------------------ *
 * Flow
 * ------------------------------------------------------------------ */
section('Question flow');

w('Sixteen questions in four groups, every one optional, then the good cause question.');
blank();
json.groups = [];
for (let i = 0; i < A.GROUPS.length; i++) {
  const g = A.GROUPS[i];
  w('**Group ' + (i + 1) + ': ' + g.title + '**');
  blank();
  const gj = { title: g.title, questions: [] };
  for (const id of g.ids) {
    const q = A.Q_BY_ID[id];
    if (!q) continue;
    const bits = [q.type];
    if (q.showIf) bits.push('only if `' + q.showIf.id + '` = "' + q.showIf.val + '"');
    if (q.exemptOn) bits.push('exempts on "' + q.exemptOn + '"');
    w('- `' + id + '` (' + bits.join(', ') + ')');
    gj.questions.push({ id, type: q.type, showIf: q.showIf || null, exemptOn: q.exemptOn || null });
  }
  blank();
  json.groups.push(gj);
}
w('Only one question is conditional: `housingFollowup`, shown when `housing` is "no".');
w('Everything else is always shown, and may be left blank.');
blank();

/* ------------------------------------------------------------------ *
 * Thresholds
 * ------------------------------------------------------------------ */
section('Numbers, and who has to confirm them');

w('| Value | Currently | Citation |');
w('|---|---|---|');
w('| Weekly earnings that exempt | $' + S.WORK_INCOME_THRESHOLD + ' before taxes | |');
w('| Massachusetts minimum wage | $' + S.MA_MIN_WAGE + ' an hour | |');
w('| Hours a week at minimum wage that exempt | ' + S.WORK_HOURS_AT_MIN_WAGE + ' | |');
w('| Hours a week counted below minimum wage | ' + S.WORK_HOURS_COMPLIANCE + ' | |');
w('| Age the rules apply to | 18 or older and under 65 | |');
blank();
w('Income and hours were last verified November 2025 and still need an expert. MLRI\'s ABAWD');
w('article on MassLegalHelp was reviewed February 2026 and is therefore newer than they are.');
blank();
w('The age wording was settled on 2026-07-30. The article says "between 18 and 65", which');
w('does not say whether a 65-year-old is included, and the federal rule caps at 64 with 65');
w('and over exempt by age. Reading the article literally would have screened a 65-year-old');
w('as subject to the rules, so the screener says "18 or older and under 65" instead. Same');
w('range, no ambiguity. Worth confirming that reading of the rule.');
blank();
json.thresholds = {
  weeklyIncome: S.WORK_INCOME_THRESHOLD,
  minimumWage: S.MA_MIN_WAGE,
  hoursAtMinimumWage: S.WORK_HOURS_AT_MIN_WAGE,
  hoursBelowMinimumWage: S.WORK_HOURS_COMPLIANCE,
  ageRange: '18 or older and under 65',
  lastVerified: '2025-11'
};

/* ------------------------------------------------------------------ *
 * Worked examples, usable as port tests
 * ------------------------------------------------------------------ */
section('Worked examples');

w('Real inputs through the real engine. A port is correct when it reproduces this table, so');
w('these double as test cases; the JSON carries them in a form a test generator can read.');
blank();
const CASES = [
  { name: 'Nothing answered', a: {} },
  { name: 'Under 18 or over 64', a: { ageRange: 'no' } },
  { name: 'Pregnant', a: { ageRange: 'yes', pregnant: 'yes' } },
  { name: 'Lives with a child under 14', a: { ageRange: 'yes', child14: 'yes' } },
  { name: 'Earns $217.50 a week or more', a: { ageRange: 'yes', working: 'income_weekly' } },
  { name: '30+ hours below minimum wage', a: { ageRange: 'yes', working: 'hours_30' } },
  { name: 'Gets SSI or SSDI', a: { ageRange: 'yes', disability: ['ssi_ssdi'] } },
  { name: 'Other disability payment only', a: { ageRange: 'yes', disability: ['other'] } },
  { name: 'No place to sleep, no diploma', a: { ageRange: 'yes', housing: 'no', housingFollowup: ['steady_job'] } },
  { name: 'No place to sleep, diploma and steady job', a: { ageRange: 'yes', housing: 'no', housingFollowup: ['diploma', 'steady_job'] } },
  { name: 'No place to sleep, none of these apply', a: { ageRange: 'yes', housing: 'no', housingFollowup: NONE } },
  { name: 'Safety concern', a: { ageRange: 'yes', dv: 'yes' } },
  { name: 'Several exemptions at once', a: { ageRange: 'yes', child14: 'yes', pregnant: 'yes', working: 'income_weekly' } },
  { name: 'No exemption, transport problem', a: { ageRange: 'yes', goodcause: 'transport' } },
  { name: 'No exemption, no good cause', a: { ageRange: 'yes', goodcause: NONE } }
];
w('| Example | Outcome | Reasons recorded |');
w('|---|---|---|');
json.examples = [];
for (const c of CASES) {
  const rt = outcome(c.a);
  const r = reasons(c.a);
  w('| ' + c.name + ' | `' + rt + '` | ' + (r.length ? r.join('; ') : '*none*') + ' |');
  json.examples.push({ name: c.name, answers: c.a, expect: { outcome: rt, reasons: r } });
}
blank();

/* ------------------------------------------------------------------ *
 * Porting notes
 * ------------------------------------------------------------------ */
section('Notes for the Docassemble port');

w('Structural mismatches to plan around, rather than discover.');
blank();
w('Docassemble asks for a variable when something needs it. This screening asks everything');
w('up front in groups and lets any of it stay blank. A group maps to one `question` block');
w('with several `fields`, each `required: False`, which keeps them defined so the decision');
w('code never triggers a question of its own.');
blank();
w('The none-of-these sentinel is a real value here, `' + NONE + '`, and it is not the same as');
w('unanswered. The housing table above shows the two producing opposite outcomes. A port');
w('using an empty checkbox set for both would be wrong.');
blank();
w('Answers persist in the browser for 24 hours and nothing is transmitted. On a Docassemble');
w('server they become session data under the host\'s retention policy. That is a change in');
w('what the tool can honestly claim, not just where it runs.');
blank();
w('The printable statement is generated in the browser today. It maps onto an `ALDocument`');
w('from a DOCX template, and filling DTA\'s own self-declaration PDF would fit the Assembly');
w('Line pipeline better than generating a letter.');
blank();
w('The big Yes/No tiles are a deliberate departure from stock Docassemble question screens.');
w('Preserving them means custom CSS in the package, not the default question library.');
blank();

fs.writeFileSync(path.join(ROOT, 'DECISION-SPEC.md'), lines.join('\n').replace(/\n{3,}/g, '\n\n') + '\n', 'utf8');
fs.writeFileSync(path.join(ROOT, 'decision-spec.json'), JSON.stringify(json, null, 2) + '\n', 'utf8');

console.log('Wrote DECISION-SPEC.md and decision-spec.json');
console.log('  ' + json.simpleExemptions.length + ' single-answer exemptions');
console.log('  ' + json.housingTruthTable.length + ' housing rows (exhaustive)');
console.log('  ' + json.examples.length + ' worked examples');
if (mismatches.length) {
  console.error('  PROBLEM: the prose description of the housing rule disagrees with the table.');
  process.exit(1);
}
